### PR TITLE
Add monitoriung elasticsearch cluster status

### PR DESCRIPTION
**Pull request by awislowski**
allow to monitor cluster status, for graphite metrics status it is converted into number value. 
Green => 2, Yellow => 1, Red => 0

### CODE REVIEW

**Comment by basigabri** [comment]
Just a question ....
Does this supports distinct envs ? eg

instances = @host1:9200,@host2:9200
cluster = True
host = host1.com,host2.com

**Comment by awislowski** [comment]
It will support as well as other options from method: collect_instance_cluster_stats. 
They will be prefixed with hostname. In out installations we use also variable path_prefix to add cluster_name for the exported metrics names into graphite.

**Comment by basigabri** [comment]
I want to attack distinct Es endpoints, with distinct path_prefixes. How can this be done with one ElasticSearchCollector.conf file ? Is there any commits that achieve this ?

**Comment by awislowski** [comment]
in the ansible module configuration file (diamond.yml)
I have added: 
path_prefix: "my string with cluster name"

**Comment by basigabri** [comment]
Yes, I understand. But the question is how do I monitor several clusters.
escluster1, escluster2. Which should be the config ?

**Comment by awislowski** [comment]
OK, I understand. I have used it always as one diamond instance for one node.

I have prepared branch with idea how to change metrics to contain also cluster_name:
https://github.com/awislowski/Diamond/commits/multi-cluster

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new pull request there if this issue is not resolved with the current code there.

Thanks!

**Pull request closed without merging**
